# Generated by Django 3.2.9 on 2022-01-14 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20220114_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bullet',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='lists.list'),
        ),
    ]
